# Generated by Django 4.2 on 2025-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_by',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_by_username',
            field=models.CharField(default='guest', max_length=255),
        ),
    ]
